
#define PASSENGERS_NUMBER 9000
#define GATE_NUM 3
#define FERRY_NUM 2
#define FERRY_START_TAKING_PASSENGERS_TIME 0
#define FERRY_WAIT_FOR_PASSENGERS_TIME 0
#define FERRY_CAPACITY 20
#define GANGWAY_CAP 10
#define MIN_BAGGAGE_LIMIT 10
#define MAX_BAGGAGE_LIMIT 15
#define MAX_COURSE_TIME 60
#define MIN_COURSE_TIME 40
#define PASSENGERS_QUEUE_SIZE 2000

#define VIP_CHANCE 100  // 10% <-> 100
#define MALE_CHANCE 500 // 50% <-> 500
#define MIN_PASSENGER_LUGGAGE 0
#define MAX_PASSENGER_LUGGAGE 20

#define LOG_ENV "CURRENT_RUN_LOG"
#define IPC_PASSENGER_QUEUE_ENV "IPC_ID"
#define SEM_ENV "SEM_ID"
#define WAITING_ROOM_ID "IPC2_ID"
#define SHM_LUGGAGE_ENV "SHM_LUGGAGE"
#define SHM_PASSENGERS_ENV "SHM_PASSENGERS"
#define SHM_GENDER_SWAP_ENV "SHM_GENDER"
#define SHM_LAST_GENDER_ENV "SHM_LAST_GENDER"
#define SHM_PASSENGERS_WAITING_ROOM "PASSENGERS_WAITING_ROOM"

#define SEM_IPC_PASSENGER_QUEUE 0
#define SEM_LOG 1
#define SEM_GATE_START 2
#define SEM_FERRY_CAP 3
#define SEM_IPC_WAITING_ROOM 4
#define SEM_MAX_LUGGAGE_SHM 5
#define SEM_SHM_PASSENGERS 6
#define SEM_SHM_GENDER 7
#define SEM_PEOPLE_AT_GANGWAY 8
#define SEM_QUEUE_FERRIES 9
#define SEM_PASSENGER_CREATED 10
#define SEM_ORCHESTRATOR_MOVE_NEXT 11
#define SEM_FERRY_MOVE_NEXT 12
#define SEM_WAITING_ROOM_CAP 13
