
#define PASSENGERS_NUMBER 20
#define GATE_NUM 3
#define FERRY_NUM 4
#define FERRY_WAIT_TIME 30
#define FERRY_COURSE_TIME 30
#define FERRY_CAPACITY 10
#define GANGWAY_CAP 5
#define MIN_BAGGAGE_LIMIT 10
#define MAX_BAGGAGE_LIMIT 15

#define VIP_CHANCE 100 // 10% <-> 100
#define MALE_CHANCE 500 // 50% <-> 500
#define MIN_PASSENGER_LUGGAGE 0
#define MAX_PASSENGER_LUGGAGE 20

#define LOG_ENV "CURRENT_RUN_LOG"
#define IPC_ENV "IPC_ID"
#define SEM_ENV "SEM_ID"
#define WAITING_ROOM_ID "IPC2_ID"
#define SHM_LUGGAGE_ENV "SHM_LUGGAGE"
#define SHM_PASSENGERS_ENV "SHM_PASSENGERS"

#define SEM_IPC 1
#define SEM_LOG 2
#define SEM_FERRY 3
#define SEM_FERRY_CAP 4
#define SEM_END 5
#define SEM_LEAVE_PORT 6
#define SEM_TAKE_PASSENGERS 7
#define SEM_IPC2 8
#define SEM_GANGWAY 9
#define SEM_MAX_LUGGAGE_SHM 10
#define SEM_FERRY_START 11
#define SEM_SHM_PASSENGERS 12
